version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bringee-container
        restart: always
        ports:
            - '${APP_PORT}:${APP_PORT}'
